# Generated by Django 5.1.4 on 2025-05-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chathistory_threatdetection"),
    ]

    operations = [
        migrations.AddField(
            model_name="threatdetection",
            name="recommendation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
